### ISSUE TITLE
Maximized Borked

### ISSUE THREAD

**Issue by GreatGodApollo** [Crystal-Development/crystal-chrome-theme#1]
When you maximize the chrome window the theme becomes borked (see below)

I am not personally a theme developer so I can't help you there, sorry!

(Image broken due to image host shutdown)

**Comment by Stebulous** [comment]
![image](https://user-images.githubusercontent.com/26839273/39647360-9ea161b4-4fac-11e8-9a70-52c94b4b2f80.png)

im pretty sure ive since fixed this but your image is invalid
